# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3722aeaf78ee1a3b2fbb11f325eccc8d2bb8240f3c2706733e3f9e18213e493c30666bb61cbac3f851784f22c81d5649a80bc16a2787dba726851a81fe92981

test:
  secret_key_base: 7f54a8351e8bfb5a224a9650cafd8c2fca6c661a6579673346b900635281470425245d1a55c595cf05f7671c7dcd7b402aa467e22193181003420b59208574df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
